- name: "UFW - Allow HTTP on port 80"
  ufw:
    rule: allow
    port: '80'

- name: Creating the wordpress folder in apache dir
  file:
    path: '{{vhost_conf_dir}}{{domain}}'
    state: directory
    recurse: yes
    owner: www-data
    group: www-data
        
- name: Setting the virtual host config
  copy:
    src: wordpress.conf
    dest: /etc/apache2/sites-available/wordpress.conf

- name: Enabling config file for apache
  apache2_module:
    state: present
    name: rewrite

- name: enabling domain for apache2
  command: a2ensite wordpress.conf

- name: disabling the default conf file
  command: a2dissite 000-default.conf