- name: Remove all anonymous user accounts
  mysql_user:
    name: ''
    host_all: yes
    state: absent
    login_user: root
    login_password: "{{ mysql_root_pass }}"

- name: Remove the MySQL test database
  mysql_db:
    name: test
    state: absent
    login_user: root
    login_password: "{{ mysql_root_pass }}"

- name: Creates database for WordPress
  mysql_db:
    name: "{{ database }}"
    state: present
    login_user: root
    login_password: "{{ mysql_root_pass }}"

- name: Create MySQL user for WordPress
  mysql_user:
    name: "{{ mysql_user }}"
    password: "{{ mysql_pass }}"
    priv: "{{ database }}.*:ALL"
    state: present
    login_user: root
    login_password: "{{ mysql_root_pass }}"
    notify:
    - Restart MySQL