- name: Extracting wordpress files
  unarchive:
    src: https://wordpress.org/latest.tar.gz
    dest: /tmp/
    remote_src: yes

- name: Just a second --- making things simpler :)
  copy: remote_src=True src=/tmp/wordpress/ dest=/var/www/html

- name: Ensuring permissions are taken care of.
  command: find /var/www/html/ -type d -exec chmod 750 {} \;

- name: Final permissions taken care of.
  command: find /var/www/html/ -type f -exec chmod 640 {} \;

- name: Adding wp-config
  command: mv /var/www/html/wp-config-sample.php /var/www/html/wp-config.php

- name: Setting Credentials DB_NAME
  lineinfile:
    path: /var/www/html/wp-config.php
    regexp: ^[a-z]*\(\s\'[DB_NAME]*\'+,\s\'+(.*)
    line: define( 'DB_NAME', '{{database}}');

- name: Setting Credentials DB_USER
  lineinfile: 
    path: /var/www/html/wp-config.php
    regexp: ^[a-z]*\(\s\'[DB_USER]*\'+,\s\'+(.*)
    line: define( 'DB_USER', '{{mysql_user}}');

- name: Setting Credentials DB_PASSWORD
  lineinfile: 
    path: /var/www/html/wp-config.php
    regexp: ^[a-z]*\(\s\'[DB_PASSWORD]*\'+,\s\'+(.*)
    line: define( 'DB_PASSWORD', '{{mysql_pass}}');

- name: enabling access
  command: chown -R www-data:www-data /var/www/html/
  notify:
  - Restart apache2